# Linear project "Solana Playground", team Hoodies, pulled 2026-09-24.
# 47 issues, no next page.
TICKETS = [
 # id, title, status, priority, assignee, parent, labels, sheet target, note
 ("HOO-1721","Keep local projects when the project list cannot be read","In Review","Urgent","Slava","HOO-1720",["Bug"],"L",""),
 ("HOO-1720","PR #29 follow-ups: account sync","Todo","High","","",[],"L","epic over the account-sync follow-ups"),
 ("HOO-1722","Restore a project's conversation on another device and after signing back in","Todo","High","","HOO-1720",["Bug"],"L","also evidences A2 cross-device rows"),
 ("HOO-1723","Stop a stale tab from overwriting another tab's work","Todo","High","","HOO-1720",["Bug"],"L","the concurrency gap Sergey raised twice and Cat never answered"),
 ("HOO-1724","Tell a deleted project apart from a diverged one","Todo","Medium","","HOO-1720",["Bug"],"L",""),
 ("HOO-1725","Make reconcile single-flight across load, focus and switch","Todo","Medium","","HOO-1720",["Bug"],"L",""),
 ("HOO-1726","Carry a project rename to other devices","Todo","Medium","","HOO-1720",["Bug"],"L",""),
 ("HOO-1727","Keep a keypair and tutorial progress that never reached the server","Todo","Medium","","HOO-1720",["Bug"],"L","touches A2 first-sign-in import"),
 ("HOO-1728",'Close shared-browser and "keep as new" edge cases',"Todo","Low","","HOO-1720",["Bug"],"L",""),
 ("HOO-1729","Tighten /api/projects validation and align the size limit with Vercel","Todo","Low","","HOO-1720",["Bug"],"L","overlaps A1 per-user size caps"),
 ("HOO-1719","Backend selection and key recovery: a thread survives losing its key","Todo","Medium","Slava","",[],"L",""),
 ("HOO-1717","Keep the built-in wallet's secret key out of localStorage","Todo","Medium","","",["Bug"],"L","same surface as J localStorage row and HOO-867"),
 ("HOO-1685","Tell a selected stage apart from the active one in the Flow stepper","Todo","Medium","","",["Bug"],"L",""),
 ("HOO-1686","Keep the Flow header readable when a sign-in error appears","Todo","Medium","","",["Bug"],"L",""),
 ("HOO-1687","Make error messages readable instead of red on red","Todo","Medium","","",["Bug"],"L",""),
 ("HOO-1715","Move the client-v2 unit suite from Jest to vitest","Todo","Medium","Slava","",[],"M","engineering tooling, never a customer roadmap row"),
 ("HOO-634","Parallelize Playground client build on Vercel","Backlog","No priority","","",["Improvement"],"M","engineering tooling"),
 ("HOO-1633","Persist communication history for default agent integration","Done","High","Slava","",[],"A1","epic over the whole A1 lane; PRs #29/#30"),
 ("HOO-1688","Point the dev build server at a server that exists","Done","High","Slava","",["Bug"],"L",""),
 ("HOO-1651","Reflect the deployed program in the stepper after page refresh","Done","High","Slava","",["Bug"],"G","half of the persist-program-id row"),
 ("HOO-1709","Port upstream's demo-path changes behind an experimental.unstable setting","Done","Medium","Slava","",["Feature"],"L","upstream sync, PR #27"),
 ("HOO-1708","Explain what the deploy step still needs instead of letting it fail","Done","Medium","Slava","",["Feature"],"K","readiness half of the first-run row"),
 ("HOO-1707","Answer 400, not 500, to a malformed body on /api/agent and /api/mcp","Done","Medium","Slava","",["Bug"],"L",""),
 ("HOO-1615","Connect Playground to Solana Wallet Adapter","Todo","Medium","","",["Feature"],"G","RETITLE to ConnectorKit per D40"),
 ("HOO-1616","Integrate Solana Wallet Adapter for external wallet connection","Todo","Medium","","HOO-1615",["Feature"],"G","RETITLE to ConnectorKit per D40"),
 ("HOO-1617","Spike PgWallet and external wallet-adapter deploy integration","Backlog","Medium","","HOO-1615",["Feature"],"G","RETITLE to ConnectorKit per D40"),
 ("HOO-1676","Restyle the Interact instruction form to the flow design language","Todo","Medium","Slava","",["Feature"],"K","one screen of the K restyle row"),
 ("HOO-1675","Show the loaded IDL on both the Deploy and Interact steps","Todo","Medium","Slava","",["Feature"],"E","Interact-stage work adjacent to the seeds row"),
 ("HOO-1599","Add server-side rust-analyzer LSP support to the editor","In Review","Medium","Sergey","",["Feature"],"F","PR #23"),
 ("HOO-1600","Deploy the unstable server (/unstable routes) to Docker-capable infrastructure","Todo","Medium","Sergey","HOO-1599",["Feature"],"F","the Cloud Run row"),
 ("HOO-1607","Fix TypeScript declaration loader crashing on an un-bundled package when experimental.unstable is on","Backlog","Low","","",["Bug"],"F","touches the Monaco TS row"),
 ("HOO-867","Harden the flow to publish the program from client on mainnet","Backlog","No priority","","",["Bug"],"G","the mainnet disclaimer row, and more"),
 ("HOO-866","Remove known URLs from settings in Playground","Backlog","No priority","","",["Improvement"],"J","part of the localStorage config row"),
 ("HOO-484","Improve workflows for rollback and OIDC","Backlog","No priority","","",["Improvement"],"J","adjacent to the CI gate row"),
 ("HOO-1614","Allow saving playground projects to the user's GitHub","Backlog","Low","","",[],"D","the repo export/import row"),
 # Archive: closed before the September scope document existed
 ("HOO-942","Finalize deploy process updates","Done","No priority","Sergey","",[],"ARCHIVE",""),
 ("HOO-865","Deploy the client to Vercel","Done","High","Sergey","",[],"ARCHIVE",""),
 ("HOO-482","Fix current Playground workflows","Done","No priority","Sergey","",[],"ARCHIVE",""),
 ("HOO-480","First iteration to fix security vulns","Done","High","Sergey","HOO-450",[],"ARCHIVE",""),
 ("HOO-450","Decide on the direction to address the security vulnerabilities at the current setup of Playground","Done","No priority","Sergey","",[],"ARCHIVE",""),
 ("HOO-429","Sync the fork with the upstream","Done","High","Sergey","",[],"ARCHIVE",""),
 ("HOO-393","Allow running playground on macOS","Done","No priority","Sergey","",[],"ARCHIVE",""),
 ("HOO-392","Collect the tools we need to use to launch the project on GCP","Done","High","Sergey","HOO-342",[],"ARCHIVE",""),
 ("HOO-342","Make Playground work with Foundation's GCP","Done","High","Sergey","",[],"ARCHIVE",""),
 ("HOO-483","Fix build isolation","Canceled","No priority","Sergey","",[],"ARCHIVE",""),
 ("HOO-481","Finish PR for using Postgres for Playground","Canceled","No priority","Sergey","",[],"ARCHIVE",""),
 ("HOO-233","playground evaluation 2026","Canceled","No priority","Grigory Samoylov","",["estimation"],"ARCHIVE",""),
]
