#!/bin/sh
# Regenerate db/schema.sql -- the whole schema in one file, for reading and
# reviewing. Migrations remain the source of truth; this is derived.
#
# dbmate can write this itself, but it shells out to `pg_dump` on the host and
# this repo needs no host Postgres client. `pg_dump` always comes from the
# postgres:16 image instead -- the same image that serves the database. That
# matters twice over: pg_dump refuses to dump a server newer than itself, and
# its output varies between versions, which would make the CI freshness check
# fail for reasons that are not schema changes.
#
# Schema only, no owners or grants: those differ per environment and would make
# the file churn for reasons that are not schema changes. `schema_migrations`
# rows ARE included, so the file records which migrations it represents.
#
# Four lines are filtered out because they are not reproducible, and a derived
# file that changes when nothing changed cannot be checked in CI:
#
#   \restrict / \unrestrict   a fresh random nonce on every single dump
#   Dumped from/by ... version  the exact patch release, e.g. 16.15 vs 16.16
#
# The first pair guards psql against meta-command injection when a dump is
# replayed. Nothing replays this file -- it exists to be read -- so dropping
# them costs nothing and stops every re-dump from producing a diff.
set -e

cd "$(dirname "$0")/.."

IMAGE=postgres:16
SERVICE=postgres
USER_NAME=solpg
PASSWORD=solpg
DB_NAME=solpg
OUT=db/schema.sql

# Locally the database is the compose service and pg_dump runs inside it. CI has
# no compose -- Postgres there is a GitHub Actions service container -- so the
# same image runs as a one-off client against it over the host network.
if [ -n "${CI:-}" ]; then
  run_pg_dump() {
    docker run --rm --network host -e PGPASSWORD="$PASSWORD" "$IMAGE" \
      pg_dump --host 127.0.0.1 --port 5432 \
      --username "$USER_NAME" --dbname "$DB_NAME" "$@"
  }
elif docker compose -f ../compose.yaml ps "$SERVICE" 2>/dev/null | grep -q "Up"; then
  run_pg_dump() {
    docker compose -f ../compose.yaml exec -T "$SERVICE" \
      pg_dump --username "$USER_NAME" --dbname "$DB_NAME" "$@"
  }
else
  echo "The '$SERVICE' service is not running." >&2
  echo "Start it with: docker compose --profile v2 up -d $SERVICE" >&2
  exit 1
fi

reproducible() {
  sed -e '/^\\restrict /d' \
      -e '/^\\unrestrict /d' \
      -e '/^-- Dumped from database version /d' \
      -e '/^-- Dumped by pg_dump version /d'
}

{
  echo "-- Generated by \`yarn db-dump\`. Do not edit."
  echo "--"
  echo "-- Derived from db/migrations/, which is the source of truth. Regenerate"
  echo "-- after adding or editing a migration; never hand-edit this file."
  echo

  run_pg_dump --schema-only --no-owner --no-privileges --no-comments | reproducible

  echo "--"
  echo "-- Applied migrations"
  echo "--"
  run_pg_dump --data-only --table=schema_migrations --no-owner --no-privileges | reproducible
} > "$OUT"

echo "Wrote $OUT"
