# key: 1-based data row of the exported sheet (header excluded)
# value: (linear, status, evidence, wave, blocked_by, comment)
# status vocabulary: Done | In review | In progress | Todo | Backlog |
#                    Not filed | Needs confirmation | Descoped
ROWMAP = {
 # --- A1 History backend ---
 2:  ("HOO-1633","Done","HOO-1633 Done; PR #29/#30",0,"","schema shipped as provider-neutral DATABASE_URL, not Cloud SQL specifically (D39)"),
 3:  ("HOO-1633","Done","HOO-1633 Done; PR #29/#30",0,"",""),
 4:  ("HOO-1633","Done","HOO-1633 Done; D39 Better Auth",0,"","delivered as Better Auth sessions, not a hand-rolled token check"),
 5:  ("HOO-1633","Done","HOO-1633 Done; D45",0,"","one thread per project/tutorial confirmed by Cat; conversation is not bound to the agent"),
 6:  ("HOO-1729","Todo","HOO-1729 covers the size half only",2,"","D44 changed this row's meaning: no retention window, caps are abuse protection. Retention by hand only"),
 7:  ("","Needs confirmation","Sergey status ~19 Sep: synced to PostgreSQL",1,"BL-2","a Postgres exists and is reachable; which instance, and whether it is the Foundation's, is unconfirmed"),
 # --- A2 History frontend ---
 9:  ("HOO-1633","Done","Sergey status ~19 Sep; D44 localStorage",0,"",""),
 10: ("HOO-1633","Done","Sergey status ~19 Sep",0,"",""),
 11: ("HOO-1633","Done","D39 Better Auth session",0,"",""),
 12: ("HOO-1722","In progress","HOO-1722 Todo",1,"","restore path exists; the discard-local prompt is the open half"),
 13: ("HOO-1633,HOO-1722","Done","Sergey status ~19 Sep",0,"",""),
 14: ("","Not filed","",2,"","D44: nothing expires on its own, so the warning is about the signed-out cap, not about loss"),
 15: ("","Todo","",2,"","OPEN: whether the model's reasoning is stored was asked by Sergey and never answered by Cat. Implemented as no-reasoning by assumption"),
 16: ("","Not filed","",2,"","D44: clearing is an explicit user action"),
 17: ("HOO-1722,HOO-1727","In progress","HOO-1722, HOO-1727",1,"","Cat declined staging this; all local threads import at sign-in"),
 18: ("HOO-1722","In progress","Sergey status: download on a different browser",1,"","the release acceptance test"),
 # --- B History step 2 ---
 20: ("","Not filed","",3,"","D44: Cat asked for Clear Conversation explicitly. This lane is a customer request, not a nicety"),
 21: ("","Not filed","",3,"",""),
 22: ("","Not filed","",3,"","D44"),
 23: ("","Not filed","",3,"","D44"),
 24: ("","Not filed","",3,"","D45 says nothing about multi-thread; Cat asked for one thread per project. Ours to want"),
 # --- C AI rail ---
 26: ("","Not filed","",2,"",""),
 27: ("","Not filed","",2,"",""),
 28: ("","Not filed","",2,"",""),
 29: ("","Not filed","",2,"",""),
 30: ("","Not filed","",3,"","OPEN: sessionStorage vs localStorage. Project code runs same-origin (see CLAUDE.md)"),
 31: ("","Not filed","",2,"",""),
 32: ("","Not filed","",2,"",""),
 33: ("","Not filed","",2,"",""),
 34: ("","Not filed","",2,"",""),
 35: ("","Todo","CONFLICT: reported in progress to the customer",1,"","Sergey's status says the ai SDK migration is in progress. This row is the gate, and D1 rejected the Vercel AI SDK on React 17 and a Node-only core. Settle before the next status"),
 36: ("","Not filed","",3,"R-2","only if the spike says yes; D1 currently says no"),
 37: ("","Not filed","",3,"",""),
 38: ("","Not filed","",3,"",""),
 39: ("","Not filed","",3,"",""),
 40: ("","Not filed","",3,"",""),
 41: ("","Not filed","",3,"",""),
 # --- D GitHub sharing ---
 43: ("","Not filed","",2,"",""),
 44: ("","Not filed","",2,"",""),
 45: ("","Not filed","",3,"",""),
 46: ("","Not filed","",3,"",""),
 47: ("","Not filed","",2,"",""),
 48: ("HOO-1614","Backlog","HOO-1614 Backlog",3,"","OPEN against D31 and Cat's 'db to store programs & conversations' - who hosts users' code is undecided"),
 # --- E IDL 1.x and seeds ---
 50: ("","Not filed","",2,"",""),
 51: ("","Not filed","",2,"",""),
 52: ("","Not filed","",2,"",""),
 53: ("HOO-1675","Todo","HOO-1675 Todo (adjacent)",3,"","HOO-1675 is Interact-stage work, not the seeds mount itself"),
 54: ("","Not filed","",3,"",""),
 55: ("","Not filed","",4,"BL-9","blocked: no such generator found in v1 or upstream"),
 # --- F Anchor 1.2 and LSP ---
 57: ("HOO-1599","In review","HOO-1599 In Review",1,"BL-3","PR #23; merge needs Maintain on the fork"),
 58: ("","Not filed","",2,"",""),
 59: ("HOO-1600","Todo","HOO-1600 Todo, Sergey",2,"BL-1","blocked on Cloud Run access"),
 60: ("","Not filed","",2,"BL-1",""),
 61: ("","Not filed","",2,"",""),
 62: ("","Not filed","",2,"",""),
 63: ("","Not filed","",2,"",""),
 64: ("","Not filed","",2,"BL-1",""),
 65: ("","Not filed","",2,"BL-1",""),
 66: ("HOO-1607","Backlog","HOO-1607 Backlog (adjacent)",3,"",""),
 # --- G Deploys ---
 68: ("","Not filed","",4,"","D41: Kora is out of the September cut"),
 69: ("","Not filed","",4,"BL-10","D41: Kora is out of the September cut"),
 70: ("HOO-867","Backlog","HOO-867 Backlog",1,"","D40: mainnet deploys stay, with a wallet connector"),
 71: ("HOO-1615,HOO-1616,HOO-1617","Todo","HOO-1615 Todo, HOO-1616 Todo, HOO-1617 Backlog",1,"","D40: the customer named ConnectorKit on 11 Sep, a day after these three were filed as Solana Wallet Adapter. RETITLE, do not duplicate"),
 72: ("","Not filed","",2,"",""),
 73: ("","Not filed","",4,"BL-10","D41"),
 74: ("","Not filed","",4,"BL-10","D41"),
 75: ("","Not filed","",4,"","D41"),
 76: ("","Not filed","",4,"","D41"),
 77: ("","Not filed","",4,"","D41"),
 78: ("","Not filed","",4,"","D41"),
 79: ("HOO-1651","In progress","HOO-1651 Done (the refresh half)",3,"","persist-and-reflect shipped; the reaped-program half has not"),
 80: ("","Not filed","",4,"","D41: the 7-day reap is a Kora behaviour"),
 81: ("","Not filed","",4,"","D41"),
 82: ("","Not filed","",4,"","D41"),
 83: ("","Not filed","",4,"","D41"),
 84: ("","Descoped","D41",4,"BL-7","D41: mainnet through Kora may not be wanted at all. Stop chasing the Jupiter key"),
 # --- H Lesson validation ---
 86: ("","Not filed","",2,"",""),
 87: ("","Not filed","",4,"",""),
 88: ("","Not filed","",4,"",""),
 # --- I Mobile ---
 90: ("","Not filed","",3,"",""),
 91: ("","Not filed","",3,"",""),
 # --- J Infra ---
 93: ("","Not filed","",2,"BL-4",""),
 94: ("","Not filed","",2,"BL-5","Triton provides the keys; confirm referrer restriction"),
 95: ("","Not filed","",2,"BL-3",""),
 96: ("","Not filed","",2,"BL-6",""),
 97: ("","Not filed","",2,"BL-6",""),
 98: ("","Not filed","",2,"",""),
 99: ("","Not filed","",2,"",""),
 100:("HOO-866,HOO-1717","Todo","HOO-866 Backlog, HOO-1717 Todo",2,"","HOO-1717 is the sharpest case: the wallet secret key is in localStorage and project code runs same-origin"),
 101:("HOO-484","Backlog","HOO-484 Backlog (adjacent)",2,"","no CI runs recorded on the fork today"),
 # --- K Design pass ---
 103:("","Not filed","",2,"",""),
 104:("HOO-1676","Todo","HOO-1676 Todo (one screen of it)",2,"",""),
 105:("HOO-1708","In progress","HOO-1708 Done (the readiness half)",2,"","the first-run flow itself is not filed"),
}
