name: Deploy to App Engine

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    name: Deploy Playground Server
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          ref: v0.29

      - name: Set up Git to get tag
        run: |
          git fetch --tags
          TAG=$(git describe --tags --abbrev=0)
          echo "VERSION_TAG=$TAG" >> $GITHUB_ENV

      - name: Set up Cloud SDK authentication
        uses: google-github-actions/auth@v2
        with:
          token_format: 'access_token'
          credentials_json: ${{ secrets.GCP_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure GCloud
        run: |-
          gcloud config set account ${{ secrets.SERVICE_ACCOUNT }}
          gcloud config set project ${{ secrets.PROJECT_ID }}

      - name: Deploy to App Engine with specific version (no promote)
        run: |
          gcloud app deploy app.yaml \
            --version=${{ env.VERSION_TAG }} \
            --no-promote \
            --quiet